language: r
cache: packages
r_packages:
- covr
- drat
before_install:
- bash make.sh
after_success:
- Rscript -e 'library(covr); codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && 
  test $TRAVIS_BRANCH == "master" && 
  bash deploy.sh
env:
  global:
    secure: KI00gGFos3rTKCDVY2cJgwokhBuOHJ1nWKPQwQ8HAKt3oXdb6a7/5NQuAsPY3Td8oVT5d35GMnvSsogRHojyJciYB+ZkA3Ljs8pNAYwTMFRt0RzGdVDZ3RXwpg8OY3dfnQ3dfzX5+JoILgpVRLJIVylTcFZg3f7kp2k/DG2hdQEuE7q+ztHLhblry50PuwCM6QI/o2qB0xs+iJs5YY/ooXnIEuXuK8AMxBfAEZKBSl6kU1yishm/OhId1Y0JbcTmfH4GT7lOcZ8Z2vjelzswnocwKmA5Ov15/X1fNd9Jn4C6tPZ8q+Vdj7IQqDnsxy3BgS2DTb2fo7unSVVOdnngVVmmBdyxyhMMbXkpZRJynRLUpLVxmRlbr6e17QEuE6t38IKyTgsOpZnPJisyE7tHhiG3td7fekYoUmyXeqYi7eFvZB8BLjkv5AHBqvvgN9JZTVz/dzrXoY8IPG/eXG9pB9mIACf906ZyjiPfCDfjW+6+v/9A1YzBiiJ/TUgYkuB7rd7EQ/WneBoFp0TkFzi6Cl+rTy2JZXwoChtVkSlXYSf+phDZ4iaJ+S0wjQzanT9dB4uYKmzKMl7PJZSck02qzXtHJR/VVub7P5AwbBGxJNioYom60xVuvqo/51f1fQZmy0jx4MxUiYwcTwjc+0wwlFbX5yrQ2/GXXxKT4NCvFvA=
